-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 2017  Intel Corporation. All rights reserved.
-- Your use of Intel Corporation's design tools, logic functions
-- and other software and tools, and its AMPP partner logic
-- functions, and any output files from any of the foregoing
-- (including device programming or simulation files), and any
-- associated documentation or information are expressly subject
-- to the terms and conditions of the Intel Program License
-- Subscription Agreement, the Intel Quartus Prime License Agreement,
-- the Intel MegaCore Function License Agreement, or other
-- applicable license agreement, including, without limitation,
-- that your use is for the sole purpose of programming logic
-- devices manufactured by Intel and sold by Intel or its
-- authorized distributors.  Please refer to the applicable
-- agreement for further details.


-- Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
-- Created on Fri Jun 01 17:46:28 2018

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;
use IEEE.std_logic_arith.all;

--  Entity Declaration

ENTITY FILTERSEL IS
-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
PORT
(
	RESET				: IN	STD_LOGIC;
	CLK100M			: IN	STD_LOGIC;
	CLK10M			: IN	STD_LOGIC;
	CLK1M				: IN	STD_LOGIC;
	CLK100K			: IN	STD_LOGIC;
	CLK10K			: IN	STD_LOGIC;
	CLK1K				: IN	STD_LOGIC;
	FILTERCLKSEL	: IN	STD_LOGIC_VECTOR(2 downto 0);
	FILTERCLK		: OUT	STD_LOGIC
);
-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!

END FILTERSEL;


--  Architecture Body

ARCHITECTURE FILTERSEL_architecture OF FILTERSEL IS


BEGIN
	
	process (
		RESET,
		FILTERCLKSEL
	)
	begin
		if ( RESET = '0' ) then
			FILTERCLK	<= '0';
		else
			case FILTERCLKSEL is
				when "000" =>		-- 10MHz
					FILTERCLK	<= CLK10M;
				when "001" =>		-- 1MHz
					FILTERCLK	<= CLK1M;
				when "010" =>		-- 100KHz
					FILTERCLK	<= CLK100K;
				when "011" =>		-- 10KHz
					FILTERCLK	<= CLK10K;
				when "100" =>		-- 1KHz
					FILTERCLK	<= CLK1K;
				when "101" =>		-- 100MHz
					FILTERCLK	<= CLK100M;
				when "110" =>		-- 100MHz
					FILTERCLK	<= CLK100M;
				when "111" =>		-- 100MHz
					FILTERCLK	<= CLK100M;
			end case;
		end if;
	end process;

END FILTERSEL_architecture;
