// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 32-bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Tue Feb 21 18:11:39 2017

updn_to_8bit updn_to_8bit_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.up(up_sig) ,	// input  up_sig
	.dn(dn_sig) ,	// input  dn_sig
	.byteout(byteout_sig) 	// output [7:0] byteout_sig
);

